-- SYNAX Cloudflare/Supabase schema
-- Run this entire file once in Supabase SQL Editor for a NEW project.
-- The application uses the service-role key server-side; no key is exposed to the browser.

create table if not exists public.synax_state (
  id text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.synax_state enable row level security;

create table if not exists public.synax_sessions (
  token text primary key,
  user_id text not null check (user_id in ('person_1', 'person_2', 'admin')),
  session_start bigint not null,
  last_active bigint not null,
  allowed_seconds bigint not null,
  is_expired boolean not null default false,
  active boolean not null default false,
  ended_at bigint
);

create index if not exists synax_sessions_user_idx
  on public.synax_sessions (user_id, last_active desc);

alter table public.synax_sessions enable row level security;

create table if not exists public.synax_call_signals (
  id bigint generated by default as identity primary key,
  from_user_id text not null check (from_user_id in ('person_1', 'person_2')),
  target_user_id text not null check (target_user_id in ('person_1', 'person_2')),
  type text not null check (type like 'call:%'),
  call_type text check (call_type in ('voice', 'video')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists synax_call_signals_target_id_idx
  on public.synax_call_signals (target_user_id, id);

create index if not exists synax_call_signals_created_at_idx
  on public.synax_call_signals (created_at);

create index if not exists synax_call_signals_target_created_idx
  on public.synax_call_signals (target_user_id, created_at, id);

create index if not exists synax_call_signals_call_id_idx
  on public.synax_call_signals ((payload->>'callId'));

alter table public.synax_call_signals enable row level security;

-- Public upload bucket. The server uploads with the service-role key.
insert into storage.buckets (id, name, public)
values ('synax-uploads', 'synax-uploads', true)
on conflict (id) do update set public = true;
